title: Adeiye Abolanle Data Analytics Portfolio
logo: bola.png
description: A data analyst with 2years experience working across different sectors,higjly skilled in Sql,Excel,Powebi tools
#show_downloads: true
#google_analytics: 
theme: jekyll-theme-minimal
